In [204]:
import numpy as np

In [ ]:
# Generating a random matrix A
n = 5
np.random.seed(5)
A = np.round( 5*np.random.randn(n,n) )

print(A)

[[ 2. -2. 12. -1.  1.]
 [ 8. -5. -3.  1. -2.]
 [-6. -1. -2.  3. -8.]
 [-4.  6.  9. -8.  3.]
 [-5. -4. -4. -2.  5.]]


In [206]:
M = np.eye(n)

m1 = np.zeros(n)
e1 = np.zeros(n)
e1[1] = 1
for i in range(n):
    if i == 0:
        m1[i] = 0
    else:
        m1[i] = A[i][0]/A[0][0]
        
        
M = M - np.outer(m1,e1)

M*A

array([[  2.,  -0.,   0.,  -0.,   0.],
       [  0.,  15.,  -0.,   0.,  -0.],
       [ -0.,  -3.,  -2.,   0.,  -0.],
       [ -0.,  12.,   0.,  -8.,   0.],
       [ -0., -10.,  -0.,  -0.,   5.]])

In [ ]:
# Regular LU factorization
def LU_factor(A):
    n = len(A)
    L = np.eye(n)
    M = np.eye(n)
    U = A.copy()
    for k in range(n-1):
        M = np.eye(n)
        M[k+1:,k] = -U[k+1:,k]/U[k,k]
        L[k+1:,k] = U[k+1:,k]/U[k,k]
        U = M@U
    return L, U

In [208]:
L, U = LU_factor(A)
print(L@U)
print(A)

[[ 2. -2. 12. -1.  1.]
 [ 8. -5. -3.  1. -2.]
 [-6. -1. -2.  3. -8.]
 [-4.  6.  9. -8.  3.]
 [-5. -4. -4. -2.  5.]]
[[ 2. -2. 12. -1.  1.]
 [ 8. -5. -3.  1. -2.]
 [-6. -1. -2.  3. -8.]
 [-4.  6.  9. -8.  3.]
 [-5. -4. -4. -2.  5.]]


In [ ]:
# Partial pivot LU factorization
def LU_factor_pp(A):
    n = len(A)
    L = np.zeros((n,n))
    M = np.eye(n)
    U = A.copy()
    piv = np.zeros(n)
    for i in range(n):
        piv[i] = i
    for k in range(n-1):
        M = np.eye(n)
        pivotIndex = k
        maxSoFar = -1e6
        for j in range(k,n):
            if abs(U[j][k]) > maxSoFar:
                maxSoFar = abs(U[j][k]) 
                pivotIndex = j
        if pivotIndex != k:
                U[[k,pivotIndex]] = U[[pivotIndex,k]]
                L[[k,pivotIndex]] = L[[pivotIndex,k]]
        piv[k] = pivotIndex
        
        M[k+1:,k] = -U[k+1:,k]/U[k,k]
        L[k+1:,k] = U[k+1:,k]/U[k,k]
        
    
        U = M@U

    L += np.eye(n)
    
    return L, U, piv

In [329]:
L, U, piv = LU_factor_pp(A)
K,G = L, U
LU = L@U
print("PA = ",LU)
n = len(A)
P = np.eye(n)

for i in range(n):
    P[[i,int(piv[i])]] = P[[int(piv[i]),i]]

print("A = ", P.T@LU)    
print("piv = ", piv)

PA =  [[ 8. -5. -3.  1. -2.]
 [-5. -4. -4. -2.  5.]
 [ 2. -2. 12. -1.  1.]
 [-4.  6.  9. -8.  3.]
 [-6. -1. -2.  3. -8.]]
A =  [[ 2. -2. 12. -1.  1.]
 [ 8. -5. -3.  1. -2.]
 [-6. -1. -2.  3. -8.]
 [-4.  6.  9. -8.  3.]
 [-5. -4. -4. -2.  5.]]
piv =  [1. 4. 4. 3. 4.]


In [321]:
print(A)

[[ 2. -2. 12. -1.  1.]
 [ 8. -5. -3.  1. -2.]
 [-6. -1. -2.  3. -8.]
 [-4.  6.  9. -8.  3.]
 [-5. -4. -4. -2.  5.]]


In [322]:
import scipy as sc

In [323]:
lu, piv = sc.linalg.lu_factor(A)
print(lu, piv)


[[ 8.         -5.         -3.          1.         -2.        ]
 [-0.625      -7.125      -5.875      -1.375       3.75      ]
 [ 0.25        0.10526316 13.36842105 -1.10526316  1.10526316]
 [-0.5        -0.49122807  0.34514436 -7.79396325  3.46062992]
 [-0.75        0.66666667 -0.02493438 -0.59521805 -9.91261155]] [1 4 4 3 4]
