In [3]:
import numpy as np

In [89]:
def QR(A):
    m = len(A)
    n = len(A[0])
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    
    for k in range(n):
        q = A[:,k]
        for j in range(k):
            R[j][k] = np.dot(Q[:,j], A[:,k])
            q = q - np.dot(R[j][k],Q[:,j])
        R[k][k] = np.linalg.norm(q)
        q = q/R[k][k]
        Q[:,k] = q
    return Q, R
        

In [90]:
A = np.round( 5*np.random.randn(5,6) )
A

array([[ 2.,  2., -6., -3.,  2.,  7.],
       [ 0.,  0.,  2.,  8.,  5., -3.],
       [ 1.,  4.,  0., -3.,  2., -1.],
       [ 5., -5.,  1.,  5.,  3., 10.],
       [-6., -7., -1., -3.,  1.,  1.]])

In [91]:
Q,R = QR(A)

In [92]:
print(Q,R)

[[ 0.24618298  0.13513371 -0.91145125  0.28599797  0.09270705  0.09500143]
 [ 0.          0.          0.31276827  0.88481027  0.3453792  -0.45600684]
 [ 0.12309149  0.39386533  0.06682556 -0.35072868  0.837999   -0.22800342]
 [ 0.61545745 -0.7498273   0.04552211 -0.10052898  0.21631645  0.85501283]
 [-0.73854895 -0.51416729 -0.2547444  -0.04689627  0.35083255  0.        ]] [[ 8.12403840e+00  3.07728727e+00 -1.23091491e-01  4.18511069e+00
   1.84637236e+00  7.01621499e+00]
 [ 0.00000000e+00  9.19403628e+00 -1.04646228e+00 -3.79363175e+00
  -1.70565111e+00 -7.46036964e+00]
 [ 0.00000000e+00  0.00000000e+00  6.39451055e+00  6.02786698e+00
  -2.43588122e-01 -7.18481245e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  6.91071822e+00
   3.94610676e+00 -1.35390236e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   4.58808998e+00  1.28880974e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  2.92159571e-15]]


In [93]:
T = Q@R

In [94]:
print(T.round())

[[ 2.  2. -6. -3.  2.  7.]
 [ 0.  0.  2.  8.  5. -3.]
 [ 1.  4.  0. -3.  2. -1.]
 [ 5. -5.  1.  5.  3. 10.]
 [-6. -7. -1. -3.  1.  1.]]


In [95]:
D = np.array([[12,-51,4],[6,167,-68],[-4,24,-41]])
Q,R=QR(D)
print(Q,R)


[[ 0.85714286 -0.39428571 -0.33142857]
 [ 0.42857143  0.90285714  0.03428571]
 [-0.28571429  0.17142857 -0.94285714]] [[ 14.  21. -14.]
 [  0. 175. -70.]
 [  0.   0.  35.]]
